### ISSUE TITLE
project folders with a space in the name cause "project.url" reference errors

### ISSUE THREAD

**Issue by connerk** [rogue-hack-lab/rogue-hack-lab.github.io#13]
i.e. "mutant toys" and "Robot Training"
"Photo-Booth" was not problemattic

**Comment by pcunning** [comment]
Does this need to be fixed or can we add it to a contributing document?

**Comment by connerk** [comment]
I imagine a simple hook could pre-commit test this. Or gulp might be configured to handle it. When folders existed with a space, the _site/project folder contained two duplicates for the project. One with a space and one with %20

And yes, using a dash in the folder name can be stated in the template but best to mitigate the error perhaps?

**Comment by connerk** [comment]
I support this being addressed through review. no need for extensive automation.
