### ISSUE TITLE
project front matter thumbnails cannot be a url.

### ISSUE THREAD

**Issue by connerk** [rogue-hack-lab/rogue-hack-lab.github.io#14]
issue is with _includes/featured-projects.html C13:19

**Comment by pcunning** [comment]
Can we add this to contributing or the template as a reference about creating projects?

**Comment by connerk** [comment]
Sorry, I don't understand that statement..

**Comment by connerk** [comment]
This can wait. during initial launch, I don't suspect anyone will use a url'd image as the thumbnail.
this might be a good restriction anyhow, especially for the thumbnail. I can see content images being referenced outside the site but thumbnails should be more certain to exist..

**Comment by connerk** [comment]
external links are unstable.
copy assets to the project for proper encapsulation.
