### ISSUE TITLE
Add real content to all published projects prior to launch v1

### ISSUE THREAD

**Issue by connerk** [rogue-hack-lab/rogue-hack-lab.github.io#21]

**Comment by pcunning** [comment]
I did not realize we were all assigned to this I thought it was just me😭... I just pushed a lot of content updates up in a0908097547bd4e598790095fd1758f5aa6d2e6b. I would consider the content deployable but some pages could still use some love. @connerk -> 3d printing @micacardillo -> mutant toys

**Comment by connerk** [comment]
This is a stale issue, and not specific, and thus hard to ever close. (AND logic for ALL project sites?) never gonna happen. 🗡 
additional information requests to a published project site warrant their own explicit issue.
