### ISSUE TITLE
Slide Out Nav - pop-over v. page-shift

### ISSUE THREAD

**Issue by connerk** [rogue-hack-lab/rogue-hack-lab.github.io#4]
[Desktop, Chrome]
When the scrollbar opens, it shifts the page content out of the way.
perhaps it should pop over the top of the page only while open for use and automatically close if the user does not make a selection from it.

**Comment by pcunning** [comment]
I vote for keeping the page shift. With the drop shadow I think it makes more sense and it is more intuitive on mobile.

**Comment by connerk** [comment]
Zero people other than @connerk have complained about this current meta driven behavior in 2.5 years. stop bike shedding, @connerk.
