### ISSUE TITLE
slack in iframe content is inconsistent with site style

### ISSUE THREAD

**Issue by pcunning** [rogue-hack-lab/rogue-hack-lab.github.io#6]

**Comment by connerk** [comment]
@pcunning, any idea what this is about? the slack widget seems fine to me. can a description be added to further define what this issue is, or can the issue be closed as stale?

**Comment by pcunning** [comment]
font and stuff is different - the ifraim also does not scale appropriately and some users were having issues with the captcha in it on a phone

**Comment by pcunning** [comment]
closed with #54
